definitions:
  app.MessageListDTO:
    properties:
      data_content_type:
        type: string
      data_schema:
        type: string
      event_id:
        type: string
      is_read:
        type: boolean
      source:
        type: string
      source_group:
        type: string
      source_url:
        type: string
      spec_version:
        type: string
      summary:
        type: string
      time:
        type: string
      title:
        type: string
      type:
        type: string
      user:
        type: string
    type: object
  app.MessagePushDTO:
    properties:
      need_inner_message:
        type: boolean
      need_mail:
        type: boolean
      need_message:
        type: boolean
      need_phone:
        type: boolean
      recipient_id:
        type: integer
      subscribe_id:
        type: integer
    type: object
  app.MessageSubscribeDTO:
    properties:
      event_type:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      mode_name:
        type: string
      source:
        type: string
      spec_version:
        type: string
      user_name:
        type: string
    type: object
  controller.deletePushConfigDTO:
    properties:
      recipient_id:
        type: integer
      subscribe_id:
        type: integer
    type: object
  controller.deleteSubscribeDTO:
    properties:
      event_type:
        type: string
      mode_name:
        type: string
      source:
        type: string
    type: object
  controller.messageStatus:
    properties:
      event_id:
        type: string
      source:
        type: string
    type: object
  controller.newPushConfigDTO:
    properties:
      need_inner_message:
        type: boolean
      need_mail:
        type: boolean
      need_message:
        type: boolean
      need_phone:
        type: boolean
      recipient_id:
        type: integer
      subscribe_id:
        type: integer
    type: object
  controller.newRecipientDTO:
    properties:
      mail:
        type: string
      message:
        type: string
      phone:
        type: string
      recipient_id:
        type: string
      remark:
        type: string
    type: object
  controller.newSubscribeDTO:
    properties:
      event_type:
        type: string
      mode_name:
        type: string
      source:
        type: string
      spec_version:
        type: string
    type: object
  controller.subscribeDTO:
    properties:
      about:
        type: string
      build_creator:
        type: string
      build_env:
        type: string
      build_owner:
        type: string
      build_status:
        type: string
      count_per_page:
        type: integer
      cve_affected:
        type: string
      cve_component:
        type: string
      cve_state:
        type: string
      end_time:
        type: string
      event_type:
        type: string
      is_bot:
        type: string
      is_read:
        type: string
      issue_assignee:
        type: string
      issue_creator:
        type: string
      issue_state:
        type: string
      key_word:
        type: string
      meeting_action:
        type: string
      meeting_end_time:
        type: string
      meeting_sig:
        type: string
      meeting_start_time:
        type: string
      mode_name:
        type: string
      my_management:
        type: string
      my_sig:
        type: string
      note_type:
        type: string
      page:
        type: integer
      pr_assignee:
        type: string
      pr_creator:
        type: string
      pr_state:
        type: string
      repos:
        type: string
      sig:
        type: string
      source:
        type: string
      spec_version:
        type: string
      start_time:
        type: string
    type: object
  controller.syncUserInfoDTO:
    properties:
      country_code:
        type: string
      gitee_user_name:
        type: string
      mail:
        type: string
      phone:
        type: string
      user_name:
        type: string
    type: object
  controller.updatePushConfigDTO:
    properties:
      need_inner_message:
        type: boolean
      need_mail:
        type: boolean
      need_message:
        type: boolean
      need_phone:
        type: boolean
      recipient_id:
        type: string
      subscribe_id:
        items:
          type: integer
        type: array
    type: object
  controller.updateRecipientDTO:
    properties:
      id:
        type: string
      mail:
        type: string
      message:
        type: string
      phone:
        type: string
      recipient_id:
        type: string
      remark:
        type: string
    type: object
info:
  contact: {}
  description: This is a Message Manager Server.
  title: Message Manager
  version: "1.0"
paths:
  /message_center/config//recipient/sync:
    post:
      consumes:
      - application/json
      description: sync user info
      parameters:
      - description: syncUserInfoDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.syncUserInfoDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: SyncUserInfo
      tags:
      - recipient
  /message_center/config/push:
    delete:
      consumes:
      - application/json
      description: delete a push_config
      parameters:
      - description: deletePushConfigDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.deletePushConfigDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: RemovePushConfig
      tags:
      - message_push
    get:
      consumes:
      - application/json
      description: get push config
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/app.MessagePushDTO'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetPushConfig
      tags:
      - message_push
    post:
      consumes:
      - application/json
      description: add a new push_config
      parameters:
      - description: newPushConfigDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.newPushConfigDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AddPushConfig
      tags:
      - message_push
    put:
      consumes:
      - application/json
      description: update a push_config
      parameters:
      - description: updatePushConfigDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.updatePushConfigDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: UpdatePushConfig
      tags:
      - message_push
  /message_center/config/recipient:
    delete:
      consumes:
      - application/json
      description: remove recipient config
      parameters:
      - description: updateRecipientDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.updateRecipientDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: RemoveRecipientConfig
      tags:
      - recipient
    get:
      consumes:
      - application/json
      description: get recipient config
      responses:
        "202":
          description: Accepted
          schema:
            type: int
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetRecipientConfig
      tags:
      - recipient
    post:
      consumes:
      - application/json
      description: add recipient config
      parameters:
      - description: newRecipientDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.newRecipientDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AddRecipientConfig
      tags:
      - recipient
    put:
      consumes:
      - application/json
      description: update recipient config
      parameters:
      - description: updateRecipientDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.updateRecipientDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: UpdateRecipientConfig
      tags:
      - recipient
  /message_center/config/subs:
    delete:
      consumes:
      - application/json
      description: delete a subscribe_config by source and type
      parameters:
      - description: deleteSubscribeDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.deleteSubscribeDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: RemoveSubsConfig
      tags:
      - message_subscribe
    get:
      consumes:
      - application/json
      description: get subscribe_config
      responses:
        "202":
          description: Accepted
          schema:
            type: int
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetSubsConfig
      tags:
      - message_subscribe
    post:
      consumes:
      - application/json
      description: add a subscribe_config
      parameters:
      - description: newSubscribeDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.newSubscribeDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: AddSubsConfig
      tags:
      - message_subscribe
  /message_center/config/subs/all:
    get:
      consumes:
      - application/json
      description: get all subscribe_config
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/app.MessageSubscribeDTO'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetAllSubsConfig
      tags:
      - message_subscribe
  /message_center/config/subs_new:
    post:
      consumes:
      - application/json
      description: save custom filter
      parameters:
      - description: subscribeDTO
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.subscribeDTO'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: SaveFilter
      tags:
      - message_subscribe
  /message_center/inner:
    delete:
      consumes:
      - application/json
      description: remove message
      parameters:
      - description: messageStatus
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.messageStatus'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: RemoveMessage
      tags:
      - message_center
    get:
      consumes:
      - application/json
      description: get inner message
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/app.MessageListDTO'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetInnerMessage
      tags:
      - message_center
    put:
      consumes:
      - application/json
      description: set message read
      parameters:
      - description: messageStatus
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.messageStatus'
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: SetMessageIsRead
      tags:
      - message_center
  /message_center/inner/count:
    get:
      consumes:
      - application/json
      description: get unread inner message count
      responses:
        "202":
          description: 成功响应
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未授权
          schema:
            type: string
        "500":
          description: 系统错误
          schema:
            type: string
      summary: CountAllUnReadMessage
      tags:
      - message_center
  /message_center/inner_quick:
    get:
      consumes:
      - application/json
      description: get inner message by filter
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/app.MessageListDTO'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GetInnerMessageQuick
      tags:
      - message_center
swagger: "2.0"
